<a href="https://colab.research.google.com/github/rawleyperetz/DeepLearningPython/blob/main/introTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.__version__

'2.11.0'

In [ ]:
x = tf.constant(4)
print(x)
y = tf.ones((3,3))
print(y)
z = tf.zeros((3,3))
print(z)
ident = tf.eye(3)
print(ident)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
# to get random values
ran = tf.random.normal((3,3), mean = 0, stddev=1)
print(ran)
rand_range = tf.range(10)
print(rand_range)

tf.Tensor(
[[ 0.2540885   0.1732647  -0.28347212]
 [ 0.21346734  0.7633912  -0.2708311 ]
 [-1.6885234   0.27906528 -0.95252377]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
# elementwise 
m = tf.constant([1,2,3])
n = tf.constant([4,5,6])
summon = tf.add(m,n)
print(summon)
subt = tf.subtract(m,n)
print(subt)
multi = tf.multiply(m,n)
print(multi)
dotprod = tf.tensordot(m,n,axes=1)
print(dotprod)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)


In [ ]:
# powers 
powered = m**3
print(powered)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [ ]:
# matrix multiplication
first = tf.random.normal((2,2))
second = tf.random.normal((2,2))
mat_prod = tf.matmul(first,second)
print(mat_prod)
mat_prod2 = first @ second
print(mat_prod2)
# mat_prod has the same value as mat_prod2

tf.Tensor(
[[-2.6544995 -2.0038064]
 [ 1.8563445  1.4975083]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.6544995 -2.0038064]
 [ 1.8563445  1.4975083]], shape=(2, 2), dtype=float32)


In [ ]:
# reshaping tensors
q = tf.random.normal((2,3))
r = tf.reshape(q,(3,2))
print(q)
print(r)

tf.Tensor(
[[ 0.46844718 -0.25351256  0.4045743 ]
 [-1.3230609   0.74570173  0.03967757]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.46844718 -0.25351256]
 [ 0.4045743  -1.3230609 ]
 [ 0.74570173  0.03967757]], shape=(3, 2), dtype=float32)


In [ ]:
# conversion of tensorflow object to numpy array
x = tf.random.normal((3,3), mean = 0, stddev=2)
y = x.numpy()
print(type(y))

#conversion back to tensor
k = tf.convert_to_tensor(y)
print(k)
print(type(k))

<class 'numpy.ndarray'>
tf.Tensor(
[[-1.1428164  -2.876308   -1.1342916 ]
 [ 0.90714836  0.98345864  0.87686753]
 [ 0.61325145  3.0376334   3.4949157 ]], shape=(3, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
